name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: Tech support does not belong here. You should only file an issue here if you think you have experienced an actual bug with JSimplify.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: issue-desc
    attributes:
      label: Description of Issue
      description: A brief description of the issue encountered.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A brief description of how it is expected to work.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: A brief explanation of how to reproduce this issue.
    validations:
      required: true